function rowsFor(e,span){return Math.max(4,Math.round(e.target/span))}
function overlap(a,b){return!(a.x+a.span<=b.x||b.x+b.span<=a.x||a.row+a.rows<=b.row||b.row+b.rows<=a.row)}
function intrinsic(e,p){let width=Math.max(360,$('layout').clientWidth||720),cw=(width-G*5)/6,px=cw*p.span+G*(p.span-1),hp=p.rows*U,cpl=Math.max(8,px/7.15),lineCount=Math.max(2,Math.floor((hp-20-(e.cue?34:0))/20)),cap=Math.max(1,cpl*lineCount),fill=Math.min(1,e.chars/cap),lineCost=cpl<34?(34-cpl)*1.7:cpl>72?(cpl-72)*1.35:0,fillCost=fill<.55?(.55-fill)*155:fill<.72?(.72-fill)*24:0,aspect=px/hp,aspectCost=aspect<.72?(.72-aspect)*30:aspect>5.4?(aspect-5.4)*8:0;return{cost:clamp(lineCost+fillCost+aspectCost,0,100),fill,cpl,aspect}}
function spatialContext(p,state){let recent=state.ps.slice(-4),cost=20;if(recent.some(q=>q.x===p.x))cost-=10;if(recent.some(q=>q.x+q.span===p.x+p.span))cost-=5;if(p.x===0||p.x+p.span===6)cost-=5;if(recent.at(-1)?.span===p.span)cost+=7;return clamp(cost,0,100)}
function stability(e,p){let q=previous.get(e.id);if(!q)return 0;return clamp(Math.abs(q.x-p.x)*14+Math.abs(q.row-p.row)*.9+Math.abs(q.span-p.span)*10,0,100)}
function editorialFit(e,p,state){let m=editorialValue(e);if(!m)return 0;let prefs={referenceMaterial:[4,5],background:[3,4],fragment:[2,3],continuation:[3,4],response:[3,4],newThought:[4,5],neutral:[4]}[m.function]||[4],shape=Math.min(...prefs.map(s=>Math.abs(s-p.span)))*11,prev=state.ps.at(-1),rel=0;if(prev){let gap=Math.max(0,p.row-(prev.row+prev.rows)),sameAxis=(p.x===prev.x||p.x+p.span===prev.x+prev.span);if(m.continuity>.6){rel+=Math.max(0,gap-4)*1.8;rel+=sameAxis?0:10*m.continuity}if(m.topicShift>.68){rel+=gap<5?(5-gap)*2.2*m.topicShift:0;rel+=sameAxis?8*m.topicShift:0}if(m.dependency==='dependsOnPrevious'){rel+=gap>6?(gap-6)*2:0;rel+=sameAxis?0:12}if(m.dependency==='refersToNearby')rel+=gap>10?(gap-10)*1.2:0}return clamp(shape+rel,0,100)}
function placementScore(e,p,state){let a=intrinsic(e,p),ed=editorialFit(e,p,state),ctx=spatialContext(p,state),st=stability(e,p);return{intrinsic:a.cost,editorial:ed,context:ctx,stability:st,fill:a.fill,cpl:a.cpl,aspect:a.aspect,total:(5*a.cost+2*ed+3*ctx+8*st)/18}}
function placements(e,state){let out=[];for(let span=2;span<=6;span++){let rr=rowsFor(e,span);for(let row=state.cursor;row<=state.cursor+18;row++)for(let x=0;x<=6-span;x++){let p={id:e.id,x,row,span,rows:rr};if(state.ps.some(q=>overlap(p,q)))continue;p.shape=placementScore(e,p,state);out.push(p)}}return out.sort((a,b)=>a.shape.total-b.shape.total).slice(0,32)}
function intersect(p,a,b){return Math.max(0,Math.min(p.row+p.rows,b)-Math.max(p.row,a))}
function viewportRows(){return clamp(Math.round((Math.max(520,innerHeight||720)-84)/U),54,96)}
function windowStarts(ps,V){let max=Math.max(...ps.map(p=>p.row+p.rows)),last=Math.max(0,max-V),step=Math.max(12,Math.round(V/4)),set=new Set([0,last]);for(let s=0;s<=last;s+=step)set.add(clamp(Math.round(s),0,last));ps.forEach(p=>[p.row,p.row+p.rows,p.row-V,p.row+p.rows-V].forEach(s=>set.add(clamp(Math.round(s),0,last))));return[...set].sort((a,b)=>a-b)}
function whiteField(ps,start,V){let g=Array.from({length:V},()=>Array(C).fill(0));ps.forEach(p=>{let y0=Math.max(start,p.row),y1=Math.min(start+V,p.row+p.rows);for(let y=y0;y<y1;y++)for(let x=p.x;x<p.x+p.span;x++)g[y-start][x]=1});let seen=Array.from({length:V},()=>Array(C).fill(false)),comps=[],dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(let y=0;y<V;y++)for(let x=0;x<C;x++){if(g[y][x]||seen[y][x])continue;let q=[[x,y]],k=0,cells=[],minx=x,maxx=x,miny=y,maxy=y,lat=false;seen[y][x]=true;while(k<q.length){let[cx,cy]=q[k++];cells.push([cx,cy]);minx=Math.min(minx,cx);maxx=Math.max(maxx,cx);miny=Math.min(miny,cy);maxy=Math.max(maxy,cy);if(cx===0||cx===C-1)lat=true;dirs.forEach(([dx,dy])=>{let nx=cx+dx,ny=cy+dy;if(nx>=0&&nx<C&&ny>=0&&ny<V&&!g[ny][nx]&&!seen[ny][nx]){seen[ny][nx]=true;q.push([nx,ny])}})}let bw=maxx-minx+1,bh=maxy-miny+1,box=bw*bh;comps.push({area:cells.length,bw,bh,lat,ragged:box?1-cells.length/box:0})}comps.sort((a,b)=>b.area-a.area);let total=C*V,largest=comps[0]||{area:0,bw:0,bh:0,lat:false,ragged:0},largestRatio=largest.area/total,small=comps.filter(c=>c.area/total<.03),slivers=comps.filter(c=>(c.bw===1&&c.bh>=V*.18)||(c.bh<=2&&c.bw>=3)),white=comps.reduce((s,c)=>s+c.area,0),occ=1-white/total,missing=largestRatio<.16?(.16-largestRatio)*190:largestRatio>.58?(largestRatio-.58)*55:0,fragment=small.length*3.5+Math.max(0,comps.length-5)*2.5,sliver=slivers.length*8,ragged=largest.ragged*24,occupancy=occ>.8?(occ-.8)*145:occ<.34?(.34-occ)*55:0,cost=clamp(missing+fragment+sliver+ragged+occupancy-(largest.lat?7:0),0,100);return{cost,largestRatio,components:comps.length,smallCount:small.length,sliverCount:slivers.length,occ}}
function composition(ps,start,V){let a=ps.map(p=>({p,m:intersect(p,start,start+V)*p.span})).filter(x=>x.m>0).sort((x,y)=>y.m-x.m);if(!a.length)return 80;let c=0;if(a.length>3)c+=(a.length-3)*13;if(a.length>1){let r=a[0].m/a[1].m;if(r<1.22)c+=(1.22-r)*70}return clamp(c,0,100)}
function semanticCost(ps){let vals=[];for(let i=1;i<ps.length;i++){let e=entries[i],m=editorialValue(e);if(!m)continue;let p=ps[i],q=ps[i-1],gap=Math.max(0,p.row-(q.row+q.rows)),same=(p.x===q.x||p.x+p.span===q.x+q.span),c=0;if(m.continuity>.6){c+=Math.max(0,gap-5)*2*m.continuity;c+=same?0:10*m.continuity}if(m.topicShift>.7){c+=gap<5?(5-gap)*2*m.topicShift:0;c+=same?6*m.topicShift:0}if(m.dependency==='dependsOnPrevious'){c+=gap>6?(gap-6)*2:0;c+=same?0:10}vals.push(clamp(c,0,100))}return mean(vals)}
function rolling(ps){let V=viewportRows(),wins=windowStarts(ps,V).map(start=>{let wf=whiteField(ps,start,V),comp=composition(ps,start,V),cost=(4*wf.cost+3*comp)/7;return{start,V,wf,comp,cost}}),costs=wins.map(x=>x.cost),p90=pct(costs,.9),avg=mean(costs),max=Math.max(0,...costs),roll=.5*p90+.3*avg+.2*max,worst=wins.reduce((a,b)=>!a||b.cost>a.cost?b:a,null);return{cost:roll,p90,mean:avg,max,worst,wins,whiteField:mean(wins.map(x=>x.wf.cost))}}
function metrics(ps,full=true){let area=0,shape=0,move=0,editorial=0;ps.forEach((p,i)=>{let e=entries[i],a=p.span*p.rows;area+=Math.abs(a-e.target)/e.target*100;shape+=p.shape?.intrinsic||0;editorial+=p.shape?.editorial||0;let q=previous.get(p.id);if(q)move+=Math.abs(q.x-p.x)*9+Math.abs(q.row-p.row)*1.2+Math.abs(q.span-p.span)*5});let r=full?rolling(ps):{cost:0,whiteField:0,wins:[],worst:null,p90:0,mean:0,max:0};return{m:{shape:shape/ps.length,editorial:editorial/ps.length,semantic:semanticCost(ps),area:area/ps.length,whiteField:r.whiteField,rolling:r.cost,move:move/ps.length},diag:r}}
function score(m){let s=0,z=0;Object.keys(W).forEach(k=>{s+=(m[k]||0)*W[k];z+=W[k]});return s/z}
function generate(){let beam=[{i:0,cursor:0,ps:[]}];while(beam.some(s=>s.i<entries.length)){let next=[];for(let st of beam){if(st.i>=entries.length){next.push(st);continue}for(let p of placements(entries[st.i],st)){let ps=[...st.ps,p],mm=metrics(ps,false).m;next.push({i:st.i+1,cursor:Math.max(st.cursor,p.row),ps,m:mm,s:score(mm)})}}beam=next.sort((a,b)=>a.s-b.s).slice(0,76)}let finals=beam.filter(s=>s.i===entries.length).slice(0,60);finals.forEach(s=>{let mm=metrics(s.ps,true);s.m=mm.m;s.diag=mm.diag;s.s=score(s.m)});candidates=finals.sort((a,b)=>a.s-b.s).slice(0,8);selected=0;renderAll()}
function dominant(ps){let ids=new Set,V=viewportRows();windowStarts(ps,V).forEach(start=>{let a=ps.map(p=>({p,m:intersect(p,start,start+V)*p.span})).filter(x=>x.m>0).sort((x,y)=>y.m-x.m);if(a[0]&&(a.length===1||a[0].m/(a[1]?.m||1)>1.2))ids.add(a[0].p.id)});return ids}
